apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.sunvalle.service: db
  name: db
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      io.sunvalle.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.sunvalle.network/shopping-default: "true"
        io.sunvalle.service: db
    spec:
      containers:
        - args:
            - --default_authentication_plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MYSQL_DATABASE
              value: svcishop
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: zhaojohn96/sqldb
          name: db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
status: {}
