apiVersion: v1
kind: Service
metadata:
  labels:
    io.sunvalle.service: db
  name: db
  namespace: shopping
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.sunvalle.service: db
status:
  loadBalancer: {}
