apiVersion: v1
kind: PersistentVolume
metadata:
  name: esearch-data
  namespace: shopping
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /export/pvs001/esearch-data
    server: 172.86.0.1
  persistentVolumeReclaimPolicy: Retain

