apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.sunvalle.service: esearch-data
  name: esearch-data
  namespace: shopping
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

