apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: shopping
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

