apiVersion: v1
kind: Service
metadata:
  labels:
    io.sunvalle.service: web
  name: web
  namespace: shopping
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 5000
  selector:
    io.sunvalle.service: web
status:
  loadBalancer: {}
