apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.sunvalle.service: web
  name: web
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      io.sunvalle.service: web
  strategy: {}
  template:
    metadata:
      labels:
        io.sunvalle.network/shopping-default: "true"
        io.sunvalle.service: web
    spec:
      containers:
        - env:
            - name: DB_URI
              value: mysql+pymysql://root:root@db:3306/svcishop?charset=utf8mb4
            - name: ESEARCH_URI
              value: esearch
            - name: REDIS_URI
              value: redis://redis:6379
          image: zhaojohn96/shopping_web
          name: web-app
          ports:
            - containerPort: 5000
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
